### ISSUE TITLE
Request for Profile Page Redesign

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#1]
### Overview
I am seeking a redesign of the **Profile Page** for our application. The goal is to maintain the consistent theme and style while exploring creative design possibilities to enhance the user experience.

### Design Requirements
1. **Creative Exploration**: You are encouraged to explore creative design ideas and solutions that can improve the overall aesthetics and functionality of the Profile Page.
2. **Components of Profile Page**:
    General Section:
     - [x] Profile picture
     - [x] Full name
     - [x] email id
     - [ ] country
     - [ ] Language
     - [x] Bio section
    - [x] Save Button
    
    API Keys Section:
    - [x] Openai API Key
    - [x] Gemini API Key
    - [x] Save Button

### Code Location
The code for the Profile Page is located at the following paths:
- `src/renderer/src/components/pages/ProfilePage.jsx`

I'm excited to see your creative ideas and look forward to collaborating on this project. Please let me know if you have any further questions or require additional information.

**Comment by Arcandres** [comment]
I would like to try.

**Comment by RajeshTechForge** [comment]
Hey @nishitasinghhh ,
Would you like to redesign the profile page ?

**Comment by RajeshTechForge** [comment]
Added General section in Profile Page.

**Comment by RajeshTechForge** [comment]
Added API Section in Profile Page
