### ISSUE TITLE
Introduce an Animation to Indicate AI Processing Post-Query Submissio

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#15]
I've been using our app and I've noticed that after submitting a query for AI processing, there isn't a clear indication that the system is working on it. This sometimes leaves me wondering if my request has been registered.

**Enhancement Suggestion:**
I believe it would greatly enhance the user experience if we could introduce a small animation (like some loading line or a pulsating dot) that activates post-query submission. This visual cue would serve as a confirmation that the AI is processing the request and we just need to hang tight for a moment.

**Benefits:**
- Provides immediate feedback to the user, ensuring them that their action has been acknowledged.
- Enhances the overall interactivity of the platform.
- Reduces uncertainty and improves user satisfaction.

I’m on the lookout for enthusiastic contributors eager to tackle this enhancement. If you’re interested or have any questions, don’t hesitate to reach out to me!

**Comment by DevanshArora312** [comment]
Hey! I'd like to contribute to the issue can you please assign it to me? Also its my first time contributing so do let me know if I must keep some things in mind.

**Comment by RajeshTechForge** [comment]
Hello @DevanshArora312 ,

Welcome to our repository, we are exited for your first contribution in our repository. I've assigned the issue to you. As a first-time contributor, here's a quick checklist:

1. **Read the Issue**: Understand it thoroughly.
2. **Fork the Repository**: Fork where the issue is.
3. **Create a Branch**: Make a new branch.
4. **Make Changes**: Work on the issue.
5. **Commit and Push**: Save your changes.
6. **Submit a Pull Request**: Open one from your branch.

Feel free to ask if you need more help. Happy contributing! 🚀

**Comment by RajeshTechForge** [comment]
This enhancement is completed by Devansh Arora [@DevanshArora312 ]  🎉
