### ISSUE TITLE
Add Light Mode Support for 'Cyber Tech 01' Theme

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#17]
## Description

I've been using the **Cyber Tech 01** theme of our app for long-time and it looks amazing in dark mode! However, I'd love to have a light mode option as well. Let's make our app even more versatile by adding support for the light theme. Currently light mode of **Dawn & Dask** is set as it's light-mode.

## Steps to Implement
1. You doesn't need to write any function, the main work is selecting perfect colour for it's light theme.
2. After selecting perfect colors set the colors for all elements in the `.Cyber_Tech_01-light {` class in `App.css`.
3. **It's very easy to apply, you will get it after seeing the `App.css` file.**

## Note
Colors should maintain the legacy of 'Cyber Tech 01' 's dark mode !

I’m on the lookout for enthusiastic contributors eager to tackle this enhancement. If you’re interested or have any questions, don’t hesitate to reach out to me!

**Comment by ReeceFranklin3245** [comment]
I'm fairly new to contributing, I'd like to work on this if possible!

**Comment by RajeshTechForge** [comment]
Hello @ReeceFranklin3245 ,

We are thrilled to see your interest in contributing in our project. This improvement is nothing but selecting perfect colours, maintaining the legacy of it's dark theme. I have assigned this issue to you and we are exited to see your first contribution in our project.
And don't forget to star this Repo.

Happy contribution!

**Comment by ReeceFranklin3245** [comment]
Did you want to keep the linear gradient colors uniform across all themes like they currently are? Or am I free to get creative

**Comment by RajeshTechForge** [comment]
Generally, yes, but if you find a more suitable color, you are welcome to change it. I appreciate your preference.

**Comment by RajeshTechForge** [comment]
Completed by @ReeceFranklin3245 on pull-request #20 🎉
