### ISSUE TITLE
Add Speaker Button at Top-Rignt of AI Response Bubble

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#21]
## Description

We have small but exciting feature suggestion for our app that I think would enhance user experience significantly. We propose to add a **small speaker icon button** at the top-right corner of the AI response bubble. This button will be a **checkbox** and on click icon will be converted into mute icon and vice-versa.

### Design Alignment
The speaker button should align perfectly with the top of the AI response bubble, creating a clean and cohesive look. It's all about those little details that make the design feel intuitive and user-friendly!

Here is the sample image of how it should look like:

![speak_btn_example](https://github.com/pinacai/PINAC_Workspace/assets/78198704/04510e2d-757f-4de0-85af-b13f90c256c4)

If you’re interested or have any questions, don’t hesitate to knock me!

**Comment by akshat99812** [comment]
Can this issue be assigned to me

**Comment by RajeshTechForge** [comment]
Yes Sure. I have assigned this issue to you and am excited to see your contribution in our project.
And don't forget to start our Repo.

Happy Coding!

**Comment by Ravi-Rathod143** [comment]
Hello! I would like to work on this issue. Could you please provide more details or assign this issue to me?

**Comment by RajeshTechForge** [comment]
> Hello! I would like to work on this issue. Could you please provide more details or assign this issue to me?
> 

I have already assigned this issue to a developer as you can see.

You may like to work on another issue or any enhancement in your mind. Let me know.

**Comment by RajeshTechForge** [comment]
> Hello! I would like to work on this issue. Could you please provide more details or assign this issue to me?
> 
Hello @Ravi-Rathod143,

Would you like to work on our third upcoming theme style "Aesthetic Boundless" ? If you are interested then I will share the details with you.

**Comment by Ravi-Rathod143** [comment]
yes, please share the details.

**Comment by Ravi-Rathod143** [comment]
I’d be happy to help you with your third upcoming theme style, "Aesthetic Boundless." Please share the details, and we can get started on designing and implementing it according to your requirements.

**Comment by RajeshTechForge** [comment]
> I’d be happy to help you with your third upcoming theme style, "Aesthetic Boundless." Please share the details, and we can get started on designing and implementing it according to your requirements.

Wait a while I will share it with you soon.

**Comment by akshat99812** [comment]
Issue solved ,but not able to push the code
![Uploading Screenshot 2024-06-12 at 9.38.08 PM.png…]()

**Comment by RajeshTechForge** [comment]
> Issue solved ,but not able to push the code
> ![Uploading Screenshot 2024-06-12 at 9.38.08 PM.png…]()
> 
> 

I am not able to see the screenshot. What issue are you facing while pushing the changes?

**Comment by akshat99812** [comment]
<img width="1349" alt="Screenshot 2024-06-12 at 9 38 08 PM" src="https://github.com/pinacai/PINAC_Workspace/assets/138353837/e1b3c532-6162-4ea1-8c36-6c39bc1393b8">

**Comment by akshat99812** [comment]
akshatpatel@Akshats-MacBook-Air PINAC_Workspace % git push --set-upstream origin feat/speaker-icon-added
remote: Permission to pinacai/PINAC_Workspace.git denied to akshat99812.
fatal: unable to access 'https://github.com/pinacai/PINAC_Workspace.git/': The requested URL returned error: 403
<img width="1349" alt="Screenshot 2024-06-12 at 9 38 08 PM" src="https://github.com/pinacai/PINAC_Workspace/assets/138353837/3f9e67aa-5ae8-428a-a719-a4cd84c96651">

**Comment by RajeshTechForge** [comment]
> akshatpatel@Akshats-MacBook-Air PINAC_Workspace % git push --set-upstream origin feat/speaker-icon-added
> remote: Permission to pinacai/PINAC_Workspace.git denied to akshat99812.
> fatal: unable to access 'https://github.com/pinacai/PINAC_Workspace.git/': The requested URL returned error: 403
> <img width="1349" alt="Screenshot 2024-06-12 at 9 38 08 PM" src="https://github.com/pinacai/PINAC_Workspace/assets/138353837/3f9e67aa-5ae8-428a-a719-a4cd84c96651">
> 

I think you are trying to commit to the original repo, make sure that you are pushing it in your forked repo
