### ISSUE TITLE
Add 'Aesthetics Unbound' Theme Style

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#23]
## Description

We have our two functional theme styles, and it's time to add our third theme, **Aesthetics Unbound"**. For light and dark moods we need the aesthetic colour selection by keeping the perfect contrast (taking care of readability). Also, this theme will eliminate the chat bubble, which means there will be no chat bubble in the Chat Box conversation. Also, you may remove any other border.

The main task is to place new sets of colours in `App.css`, also need to add an option to change the theme in `SettingsPage.tsx`, there already an extra card space is given, replace it with this themed card.

I’m on the lookout for enthusiastic contributors eager to tackle this enhancement. If you’re interested or have any questions, fell free to reach out to me!

**Comment by RajeshTechForge** [comment]
Hello @Ravi-Rathod143, take a look at it and tell me if you are comfortable.

**Comment by louisv20** [comment]
I'm willing to provide this enhancement. Do you have specific colors in mind?

**Comment by RajeshTechForge** [comment]
> I'm willing to provide this enhancement. Do you have specific colors in mind?
> 

Aha.., that's a part of hit and check.

My suggestion is first you select the best combination by your choice and then show the combination.

I think this way will work better.

**Comment by louisv20** [comment]
Got it. I will try a combination of colors and upload screenshots?

**Comment by RajeshTechForge** [comment]
> Got it. I will try a combination of colors and upload screenshots?

Yup, that will be good

**Comment by louisv20** [comment]
I've made some changes and attached a couple of screenshots. Please let me know what you think!
![Screenshot (391)](https://github.com/pinacai/PINAC_Workspace/assets/163933770/f3d37908-824c-4869-a542-dd3c0d16fa60)
![Screenshot (392)](https://github.com/pinacai/PINAC_Workspace/assets/163933770/cb8d58ee-9f72-40f4-ba64-709aff34598d)

**Comment by RajeshTechForge** [comment]
Something feels off...
What about this combination for light mode?

![E_reader (reading app).jpeg](https://github.com/pinacai/PINAC_Workspace/assets/78198704/f09c4fbe-e375-4a1f-bf20-5cacef2079b5)

**Comment by louisv20** [comment]
Did some adjustments
![Screenshot (400)](https://github.com/pinacai/PINAC_Workspace/assets/163933770/12a5ab98-0e42-4203-8b43-0f6fe00924d5)
![Screenshot (401)](https://github.com/pinacai/PINAC_Workspace/assets/163933770/babe41e7-9f46-4f8a-84e0-7485640fd9ca)

**Comment by RajeshTechForge** [comment]
Nice 👍

**Comment by louisv20** [comment]
> Nice 👍

Should I submit PR with these changes?

**Comment by RajeshTechForge** [comment]
> Should I submit PR with these changes?

Yes
