### ISSUE TITLE
Enhancement : A button to stop AI from generating text.

### ISSUE THREAD

**Issue by DevanshArora312** [RajeshTechForge/pinac_workspace#27]
A new addition to the home page, when the AI types message we can add a button so that user can stop it from typing if the content seems undesirable and not wait for whole content being written to write a new prompt.

I have more or less written the code for this issue, but it involves using ContextAPI for a little complex state management . Also I have added `React-Icons` package for the icon itself. 

@RajeshTechForge , if there is no issue integrating these new features as well as the new package, I'll create a PR soon.

**Comment by RajeshTechForge** [comment]
No issue with it, it's a much awaited feature. Go ahead.
