### ISSUE TITLE
Implement Profile Image Uploader

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#30]
## Description

The current profile page is nearly complete, yet the user's profile picture remains static. Our goal is to upgrade this feature by turning the profile picture into a clickable button. This button will allow users to upload a new image, which will then be displayed on the profile page. Until a new image is uploaded by the user, the existing image will serve as the default profile picture.

Don't forget to knock me if you need any help.

**Comment by akshat99812** [comment]
where will the images be saved

**Comment by RajeshTechForge** [comment]
For now it will be saved in `backend/config` folder, we may change the folder name later.

**Note**: `config` folder is not added in .gitignore completely, add the whole folder to the .gitignore first, but don't delete the readme.

**Comment by akshat99812** [comment]
I have a doubt where do you want to store the Profile images we don't have a db yet

**Comment by RajeshTechForge** [comment]
I have updated the backend files, store them in `backend/user data/img/`. Yes, we haven't integrated the DB yet, we are going to do that in upcoming changes.

**Comment by akshat99812** [comment]
ya sure , do you want me a seprate ui page for uploading images which will be opened when the user clicks on the profile picture

**Comment by RajeshTechForge** [comment]
Yeah Ofcourse.

**Comment by akshat99812** [comment]
ya sure, will do

**Comment by MadGanGithub** [comment]
Hi @RajeshTechForge ,
 I'd like to work on this issue. Could you please assign it to me?

**Comment by RajeshTechForge** [comment]
> Hi @RajeshTechForge, I'd like to work on this issue. Could you please assign it to me?

I would be happy to assign this issue to you. Happy Coding!

**Comment by MadGanGithub** [comment]
Hi @RajeshTechForge,
I have added image upload feature and made a PR

**Comment by RajeshTechForge** [comment]
> Hi @RajeshTechForge,
> I have added image upload feature and made a PR
> 

I am impressed by your efforts to add this feature. I am currently busy, I will merge it soon.

**Comment by MadGanGithub** [comment]
If completed, this can be closed
