### ISSUE TITLE
Shifting Page Clears Chats in the ChatBox

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#31]
## Description

Our app has multiple pages along with the Chat Box, and when we switch the page the ChatBox clears all our chats with AI, and it's pretty annoying. It might be caused due to a reload for shifting the page due to our current page shifting mechanism (nothing wrong in the code for the current mechanism). We need to add an alternative way to shift the page to avoid this bug.

I’m on the lookout for enthusiastic contributors eager to tackle this enhancement. If you’re interested or have any questions, don’t hesitate to reach out to me!

**Comment by RajeshTechForge** [comment]
I found a way to fix this bug and I am working on it!

**Comment by Aardenfell** [comment]
Imma look into tackling this issue 🙂

**Comment by RajeshTechForge** [comment]
Solving this bug is going hard. I have created a separate branch in the Repo for now.

**Comment by Aardenfell** [comment]
i've been racking my head over this one and can't come up with something that works tbh

**Comment by RajeshTechForge** [comment]
> i've been racking my head over this one and can't come up with something that works tbh

Yeah, I can understand. Therefore, we have decided to make it a feature, not a bug 🙂
