### ISSUE TITLE
Design Loading Page

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#35]
## Description

In our app at starting, we have implemented a loading page, it's just the `loading.html` file. Now we need to design it to be a good-looking one.

## Requirements
- [ ] Need to design a minimal animation for the page. A simple zoom-in animation of the name "PINAC" with the slogan "Automate Your Workflow". Use the `nasalization-rg` font to replicate the logo.
- [ ] Have to use simple HTML, CSS & JS.
- [ ] All CSS and JS scripts will be within the `loading.html`

Try to keep it simple and minimal, so it loads as fast as possible. 

I’m on the lookout for enthusiastic contributors eager to tackle this enhancement. If you’re interested or have any questions, don’t hesitate to reach out to me!

**Comment by SeanAverS** [comment]
Hello, 
I'm interested in working on this. Could I please be assigned? Thank you.

**Comment by RajeshTechForge** [comment]
> Hello, 
> I'm interested in working on this. Could I please be assigned? Thank you. 


Welcome to our Project. I have assigned this to you. Excited to see your contribution in our Project.
And don't forget to star our Repo.

**Comment by RajeshTechForge** [comment]
This enhancement is completed by @SeanAverS 👏
