### ISSUE TITLE
Add Copy to Clipboard Button

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#39]
## Description

When our app answers the chat, many times we need to copy them, therefore we need to implement a copy to clipboard button at the bottom-right of the ai-answer bubble. So that every time AI shows an answer there will be a small copy to the clipboard button. It will be in the style:

![Screenshot from 2024-06-16 20-59-16](https://github.com/pinacai/PINAC_Workspace/assets/78198704/da99b248-4a00-4533-9e19-2a7cce05a189)

Also add a change in the icon or a small pop-up on clicking it, so that the user becomes sure that the text is copied.

Any enthusiastic contributor who is eager to tackle this enhancement is welcome. If you’re interested or have any questions, don’t hesitate to reach out to me!

**Comment by Subashree-selvaraj** [comment]
I'm willing to resolve this issue please assign it to me

**Comment by RajeshTechForge** [comment]
Thanks for your interest, I have assigned this issue to you. Happy Coding!

**Comment by Subashree-selvaraj** [comment]
Add Copy to Clipboard Button #39 completed

**Comment by SeanAverS** [comment]
Hello,

Is this issue still open? If it is I would like to be assigned please. Thank you.

**Comment by RajeshTechForge** [comment]
**Hi @SeanAverS**, I would be happy if you look at this feature. Happy coding!

**Comment by RajeshTechForge** [comment]
Completed by  me (@RajeshTechForge)
