### ISSUE TITLE
Automaticly Switch to Full Screen in LogIn Page

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#45]
## Description

Recently we have implemented the LogIn System in our App through our Login Page. But our Login Page is designed and optimized for full screen (because full screen gives a better login experience), so we need to add functionality so that whenever we enter the Login Page, it switches to full screen. and back to the previous width when the Login page is gone.

**Comment by renu-123-pixel** [comment]
hello! @RajeshTechForge  can i work on this issue?

**Comment by RajeshTechForge** [comment]
Yeah sure, it's a priority fix for our Log In Page. I forgot to add in the desc that you also need to implement a switch back to the previous width for HomePage.

I have assigned this issue to you. Don't forget to start our Project. Happy Contribution!

**Comment by RajeshTechForge** [comment]
Hi @renu-123-pixel, are you working on it ?

**Comment by renu-123-pixel** [comment]
Yes im working on it.
________________________________

**Comment by MadGanGithub** [comment]
Hi @RajeshTechForge ,
I would like to work on this. Can you assign me?

**Comment by RajeshTechForge** [comment]
> Hi @RajeshTechForge , I would like to work on this. Can you assign me?

I would be happy if you complete this enhancement. Happy Contribution!
