### ISSUE TITLE
Make Welcome Text Dynamic

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#49]
## Description

Currently, our welcome message displays: ***Hello, how can I help you today?*** While this is fine, we can add some dynamism to it. Let's make it time-based, so it says ***Good morning, how can I assist you?*** in general. Additionally, when the user provides their name, we'll personalize it further: ***Good afternoon, [Name], how can I help you?***

It seems a small improvement but it will greatly enhance our App's user experience. Any enthusiastic contributor who is eager to tackle this enhancement is welcome. If you’re interested or have any questions, don’t hesitate to reach out to me!

**Comment by ParthJohri** [comment]
@RajeshTechForge, Please review the PR - https://github.com/pinacai/PINAC_Workspace/pull/50

If there are any suggestions and more enhancements, please let me know, will do the necessary changes.

**Comment by RajeshTechForge** [comment]
This enhancement is completed by @ParthJohri 🎉
