### ISSUE TITLE
Add Animation for Copy Btn on Click

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#52]
## Description

We have a copy button on the AI response bubble. But the problem is that click doesn't show any effect, therefore it's confusing for use to understand whether the button is clicked or not. So, we need to apply some effect on click, it may be like changing text to copied and back to copy after some time, any pop-up, etc, free to be creative.

I’m on the lookout for enthusiastic contributors eager to tackle this enhancement. If you’re interested or have any questions, feel free to reach out to me!

**Comment by umavl6** [comment]
@RajeshTechForge I will work on this

**Comment by RajeshTechForge** [comment]
> @RajeshTechForge I will work on this

Welcome to **PINAC Workspace**. We are existed to see your contribution. Don't forget to star our Project.

**Comment by RajeshTechForge** [comment]
Enhancement completed by @AsharAmir. Closing this issue.
