### ISSUE TITLE
Add Three-dot Option Btn in Input Group

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#54]
## Description

With our tool's development, we will add new features of adding Image, PDF, and Web searching. So, we need to add an option for them in the Input Group.

## Requirement

We need to add a three-dot icon on the left of the send icon, on clicking it the option will arrive to **Add Image**, **Add PDF**, and **Web Search** (Use only the icon for it) horizontally just above the border of Input Group. Use icon from **React Icon**.

I’m looking for contributors eager to add this UI feature. If you’re interested or have any questions, feel free to reach out to me!

**Comment by joras-droid** [comment]
i would like to work on it.
can you please assign this issue to me? :)

**Comment by RajeshTechForge** [comment]
Hello @Nirajan1-droid, I would be pleased to assign you this feature request. I look forward to seeing your valuable contribution. Don't forget to star our Project.

Happy Coding!

**Comment by joras-droid** [comment]
@RajeshTechForge i have made it like this:
please confirm it and provide me feedback and changes you want to implement in it.
![image](https://github.com/pinacai/PINAC_Workspace/assets/65585311/49904303-a0fe-4090-8c22-63610fb35e24)

**Comment by RajeshTechForge** [comment]
Thanks for the Preview. My suggestion is to place three-dot vertically and make the icon size of the option bigger (equivalent to send icon) for betterment. Place the option box just above the border of the Input Group for a better look.

**Comment by joras-droid** [comment]
![image](https://github.com/pinacai/PINAC_Workspace/assets/65585311/c7f3b443-80e9-4d89-8f26-6c068f763b33)
is it fine?
its just the design to confirm .

**Comment by RajeshTechForge** [comment]
Nice, confirm 👍

**Comment by joras-droid** [comment]
https://github.com/pinacai/PINAC_Workspace/assets/65585311/799a5fd2-6195-441a-9897-ec035cad3917

i have made it responsive.
do i have to make it non-responsive?
what do you think?

**Comment by joras-droid** [comment]
will be happy to make further changes

**Comment by RajeshTechForge** [comment]
Thanks for working on this feature.
