### ISSUE TITLE
Make the About Page Responsive

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#56]
## Description

We always make sure our app is responsive for any screen size, but we have observed that the About Page is not that responsive in different screen heights. 

I’m looking for contributors eager to solve this bug. If you’re interested or have any questions, just knock me!

**Screenshort**:
![Screenshot from 2024-07-08 21-37-37](https://github.com/pinacai/PINAC_Workspace/assets/78198704/7589cb45-b053-48fe-a012-61ad57d84942)

**Comment by krishchvn** [comment]
Hey. Can you assign the issue to me?

**Comment by RajeshTechForge** [comment]
> Hey there! Could you please assign this issue to me?

A contributor has submitted a pull request, and I've requested some changes. If those changes aren't made, I'll assign the issue to you.
