### ISSUE TITLE
Add Cross Button for Canceling Uploded Img

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#63]
## Description

We’ve introduced an image uploader option and image preview in our app. However, currently, users cannot cancel an uploaded image, which is a critical feature we need. To address this, we need to add a cross button to the top-right corner of the image preview, allowing users to cancel their uploads. This straightforward enhancement is crucial for our app’s usability.

I’m on the lookout for enthusiastic contributors eager to tackle this enhancement. If you’re interested or have any questions, feel free to reach out to me!

**Comment by SeanAverS** [comment]
Hello, 

I'm interested on working on this. Could I please be assigned? Thanks.

**Comment by RajeshTechForge** [comment]
> Hello, 
> 
> I'm interested on working on this. Could I please be assigned? Thanks. 

I have assigned this issue to you. Thank you for your interest.
