### ISSUE TITLE
Add Support Options to Sidebar

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#65]
## Description:

We need to enhance our AI chatbot app's sidebar by adding a **Support** dropdown menu with the following options:

1. **Report Bug**
2. **Feature Request**
3. **Product Wiki**

This addition will improve user experience by providing easy access to key support functions.

## Specifications:

- Add a **Support** item to the sidebar with a dropdown arrow
- When expanded, show 3 options: _Report Bug_, _Feature Request_, and _Product Wiki_
- Ensure the design matches our app's existing UI style and color scheme
- Use appropriate icons for each option if consistent with our current design language

## Dropdown Design Details

1. On expanding the sidebar dropdown will be in the given image style:

![Screenshot from 2024-07-16 07-40-43](https://github.com/user-attachments/assets/7e8538c1-f404-44e9-a02f-295a729ed50d)
![Screenshot from 2024-07-16 07-40-55](https://github.com/user-attachments/assets/9853e6b5-cd0d-47d3-8037-928cdc34dbc0)

2. When the Sidebar is not expanded then on clicking the **Sidebar Option**  the options will arrive beside the sidebar on a floating tab.

---
This enhancement is a great opportunity for motivated individuals to get involved. If you're interested or have any inquiries, please don't hesitate to knock me.

**Comment by wyliemickelson** [comment]
Hi, you can assign this to me

**Comment by RajeshTechForge** [comment]
> Hi, you can assign this to me

Hi @wyliemickelson, I have assigned this important feature request to you. Waiting to see your another crucial contribution.

**Comment by RajeshTechForge** [comment]
Hi @wyliemickelson, are you working on it ?
