### ISSUE TITLE
Add Advance Input Option

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#69]
## Description

Now we have to implement the advanced input options, for that, we need to add **3 dropdown-menu** just above the user input area.

## UI Requirements

1. All these options should be dropdown
2. Dropdown-menu's options will appear on the upper side so that it doesn't block the user input area.
3. This will be placed inside the `input_box` class of `InputPanel.tsx`
4. Create a separate component for **dropdown-menu** in the Home Page component.
5. Use the React icon for icons.
6.  For large screens, all these dropdowns will stay side by side (with all 3 they must cover equal to the width of the input group).
7. For the Narrow screen, only one will appear at a time, and the next button will be beside it to change the dropdown.

![Untitled(1)](https://github.com/user-attachments/assets/1de2c3a9-70e8-4190-8eb5-6713294c278e)

---

This enhancement is a great opportunity for motivated individuals to get involved. If you're interested or have any inquiries, please don't hesitate to get in touch with me.

**Comment by sriabhinay556** [comment]
for larger screens, is it 3-options or 3-drop-downs to be displayed side-by-side?

**Comment by RajeshTechForge** [comment]
> for larger screens, is it 3-options or 3-drop-downs to be displayed side-by-side?

Hi @sriabhinay556, it's three dropdowns to to displayed side by side for a large screen.

**Comment by sriabhinay556** [comment]
I can provide 3 drop-downs for large screens, and you'll be having only 1 drop-down for smaller screens, which is not tallying up.
Can you provide more context about the requirement. 

For larger screens:
1. What are the 3 drop-down names?
2. What are the options for each drop-down?

For smaller screens:
1. What is the drop-down name (only 1 here)
2. What are the options?

**Comment by RajeshTechForge** [comment]
> I can provide 3 drop-downs for large screens, and you'll be having only 1 drop-down for smaller screens, which is not tallying up. Can you provide more context about the requirement.
> 
> For larger screens:
> 
>     1. What are the 3 drop-down names?
> 
>     2. What are the options for each drop-down?
> 
> 
> For smaller screens:
> 
>     1. What is the drop-down name (only 1 here)
> 
>     2. What are the options?

Sorry for the misclassification, For now, keep the dropdown name as Dropdown1,..2,..3. Along with some random option in them (We will update those options later). 
There will be 3 dropdowns also on the narrow screen but will be shown only one at a time. The next button will be beside it for a narrow screen to change the dropdown.

**Comment by sriabhinay556** [comment]
Got it. Thanks for clarifying, I will be working on it soon

**Comment by RajeshTechForge** [comment]
Hey @sriabhinay556, are you working on it ?

**Comment by sriabhinay556** [comment]
Have you committed my contribution? I am new to open source and I do not
understand this. This commit SHA: e6f6492351264fb1ded03e1451fbcdbd20918565
says that my changes are committed to yours main. You can find that here:
https://github.com/pinacai/PINAC_Workspace/pull/70/commits
If that happened, why can't I see my commit in your commit section of the
project?
Really appreciate if you can clarify this. Thanks.

**Comment by RajeshTechForge** [comment]
For your clarification, I have closed that pull request, not merged because you haven't done the requested changes. This Issue is also closed as completed because I have completed this feature request.

If you want to contribute to this Project choose from an open issue. Always comment on the issue that you are interested in working on in any Repository. If you have any further doubt you can ask me.

**Comment by sriabhinay556** [comment]
I thought to work on it but it was late by that time. Thanks for clarifying

**Comment by RajeshTechForge** [comment]
Hi @sriabhinay556, if you want to contribute to the open source, I can guide you to contribute to our Project. You just need time to work on it.
