### ISSUE TITLE
Add Uploaded PDF Preview

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#71]
## Description

We have options in the App to upload Images & PDFs as attachments. We have already added the Uploaded image preview, now we need to add the PDF preview.

## Requirements

The design will be the same as the image preview. Instead of the image place, it will show the PDF name and "PDF" written at the bottom.

I’m on the lookout for enthusiastic contributors eager to tackle this enhancement. If you’re interested or have any questions, feel free to reach out to me!

**Comment by DavidReque** [comment]
I would like to work on it, can you assign it to me?
