### ISSUE TITLE
Add Transition Effect for Menubar & Settings Pages

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#76]
## Description

We have a Menubar component currently used in the Settings Page, but it currently lacks any transition effects. We need to add transition effects to the Menu bar. This little improvement will significantly improve the user experience of our application.

## Requirement
- Add a transition effect for Menubar.

If anyone is interested in contributing to this project through this improvement are highly welcome. For any questions or doubts don't hesitate to knock me!

**Comment by subhamc88** [comment]
What kind of transitions are you expecting ?

**Comment by RajeshTechForge** [comment]
When we shift the option in menu bar, it shifts instantly, instead I want animation to see the highlight colour switching from one to another.

(We don't need any animation for rest page)
