### ISSUE TITLE
Add Live Search Button

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#77]
## Description

We need to add a **Live Search** button in our app to switch on/off the AI answer feature to research the internet on the query. 

## Button Specification
* Add the button on the top-right side (left side of the new chat button)
* Use _React Icon_ for icon
* It will be responsive, same as the new chat button
* Follow the design given in the image

![Live Search Button (1)](https://github.com/user-attachments/assets/9812b278-ce10-40e3-afa6-cf8999fe2f5f)

I’m on the lookout for enthusiastic contributors eager to tackle this enhancement. If you’re interested or have any questions, feel free to reach out to me!

**Comment by DevanshArora312** [comment]
Hello again Rajesh, I hope you are doing well. If the issue is still up for grabs, please assign it to me, I have created the button locally and can create a PR soon if needed.
Thanks!

**Comment by RajeshTechForge** [comment]
Nice to see you again @DevanshArora312 . This issue is still up. I would appreciate it if you could submit your changes as a pull request.
