### ISSUE TITLE
Add Session Delete Button with Animation

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#79]
## Description

Currently, in the Chat History, we can't delete the sessions, therefore we need to add a delete button for each session card. This deleted button will be hidden and uncovered on hover like in the video given below

https://github.com/user-attachments/assets/3f0dcc66-ffef-493a-8b64-253b19351058

The delete button design will be the same as the trash icon shown in the video. If anyone is interested in contributing to this project through this improvement are highly welcome. For any questions or doubts don't hesitate to knock me!

**Comment by tuxy-streamer** [comment]
I would like to resolve this issue.

**Comment by RajeshTechForge** [comment]
> I would like to resolve this issue.

I would appreciate it if you could work on it after resolving your runtime error.
