### ISSUE TITLE
Add Like & Dislike button on AI response bubble

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/pinac_workspace#90]
## Description

We need to add like and dislike buttons to the AI response bubble, positioned to the right of the copy button. Please use React Icon for the icons.

For taking inspiration: 
![Screenshot 2024-10-27 212016](https://github.com/user-attachments/assets/b557ff32-63d7-42e4-8b10-8ccbe2f04c81)

If anyone is interested in contributing to this project through this improvement, they are highly welcome. If you have any questions or doubts, don't hesitate to ask me!

**Comment by Shaiq1217** [comment]
I can work on this, please assign this to me!

**Comment by RajeshTechForge** [comment]
> I can work on this, please assign this to me!
> 
I have assigned this issue to you. Happy coding!
